version: '3.8'

services:
  app:
    container_name: flexpad
    restart: always
    image: faletti/flexpad:release-1.0.0
    build:
      context: ./
      target: production
      dockerfile: Dockerfile
    volumes:
        - .:/app
        - /app/node_modules
        - /app/.next
    ports:
      - "3000:3077"